"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basetenerror import BasetenError
from typing import Any, TYPE_CHECKING

from baseten.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierror import APIError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError
    from .security import Security, SecurityTypedDict
    from .transcribeaudioop import (
        AsrOptions,
        AsrOptionsTypedDict,
        Audio,
        AudioTypedDict,
        One,
        OneTypedDict,
        Segments,
        SegmentsTypedDict,
        Three,
        ThreeTypedDict,
        TranscribeAudioAudiosResponseBody,
        TranscribeAudioAudiosResponseBodyTypedDict,
        TranscribeAudioRequestBody,
        TranscribeAudioRequestBodyTypedDict,
        TranscribeAudioResponse,
        TranscribeAudioResponseBody,
        TranscribeAudioResponseBodyTypedDict,
        TranscribeAudioResponseTypedDict,
        Two,
        TwoTypedDict,
        WhisperInput,
        WhisperInputTypedDict,
        WhisperParams,
        WhisperParamsTypedDict,
    )

__all__ = [
    "APIError",
    "AsrOptions",
    "AsrOptionsTypedDict",
    "Audio",
    "AudioTypedDict",
    "BasetenError",
    "NoResponseError",
    "One",
    "OneTypedDict",
    "ResponseValidationError",
    "Security",
    "SecurityTypedDict",
    "Segments",
    "SegmentsTypedDict",
    "Three",
    "ThreeTypedDict",
    "TranscribeAudioAudiosResponseBody",
    "TranscribeAudioAudiosResponseBodyTypedDict",
    "TranscribeAudioRequestBody",
    "TranscribeAudioRequestBodyTypedDict",
    "TranscribeAudioResponse",
    "TranscribeAudioResponseBody",
    "TranscribeAudioResponseBodyTypedDict",
    "TranscribeAudioResponseTypedDict",
    "Two",
    "TwoTypedDict",
    "WhisperInput",
    "WhisperInputTypedDict",
    "WhisperParams",
    "WhisperParamsTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "AsrOptions": ".transcribeaudioop",
    "AsrOptionsTypedDict": ".transcribeaudioop",
    "Audio": ".transcribeaudioop",
    "AudioTypedDict": ".transcribeaudioop",
    "One": ".transcribeaudioop",
    "OneTypedDict": ".transcribeaudioop",
    "Segments": ".transcribeaudioop",
    "SegmentsTypedDict": ".transcribeaudioop",
    "Three": ".transcribeaudioop",
    "ThreeTypedDict": ".transcribeaudioop",
    "TranscribeAudioAudiosResponseBody": ".transcribeaudioop",
    "TranscribeAudioAudiosResponseBodyTypedDict": ".transcribeaudioop",
    "TranscribeAudioRequestBody": ".transcribeaudioop",
    "TranscribeAudioRequestBodyTypedDict": ".transcribeaudioop",
    "TranscribeAudioResponse": ".transcribeaudioop",
    "TranscribeAudioResponseBody": ".transcribeaudioop",
    "TranscribeAudioResponseBodyTypedDict": ".transcribeaudioop",
    "TranscribeAudioResponseTypedDict": ".transcribeaudioop",
    "Two": ".transcribeaudioop",
    "TwoTypedDict": ".transcribeaudioop",
    "WhisperInput": ".transcribeaudioop",
    "WhisperInputTypedDict": ".transcribeaudioop",
    "WhisperParams": ".transcribeaudioop",
    "WhisperParamsTypedDict": ".transcribeaudioop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
