"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "baseten"
__version__: str = "0.1.2"
__openapi_doc_version__: str = "1.0"
__gen_version__: str = "2.517.3"
__user_agent__: str = "speakeasy-sdk/python 0.1.2 2.517.3 1.0 baseten"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
